loki:
  tolerations:
    - key: infra
      operator: Equal
      value: "true"
      effect: NoSchedule
  storage:
    bucketNames:
      chunks: homework.otus.ntikhomirov.2024
      admin: s2a
      ruler: s2a
    type: 's3'
    s3:
      endpoint: storage.yandexcloud.net
      secretAccessKey: {{ .Values.env.secretAccessKey }}
      accessKeyId: {{ .Values.env.accessKeyId }}
  auth_enabled: false
  commonConfig:
    replication_factor: 1

promtail:
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  enabled: true
  configServer:
    enabled: true

test_pod:
  enabled: false
