prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'frontend'
      static_configs:
        - targets: ['frontend.workspac:80']
    - job_name: 'productcatalogservice-exporter'
      static_configs:
        - targets: ['productcatalogservice-exporter.workspace:9100']

additionalPrometheusRules:
 - name: otus
   groups:
     - name: Test
       rules:
         - alert: FrontendDown
           expr: up{job="frontend"} == 0
           for: 0m
           labels:
             severity: critical
           annotations:
             summary: Frontend down (instance {{ $labels.instance }})

         - alert: ProductcataLogservice-exporter
           expr: up{job="productcatalogservice-exporter"} == 0
           for: 1m
           labels:
             severity: warning
           annotations:
             message: "Down service - ProductcataLogservice-exporter"

alertmanager:
  config:
   global:
     resolve_timeout: 5m
   route:
     group_by: ['alertname', 'instance', 'job']
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 12h
     receiver: 'null'
     routes:
       - match:
           alertname: Watchdog
         receiver: 'telegram'
         continue: true
       - match_re:
           severity: ^(none|warning|critical)$
         receiver: 'telegram'
   receivers:
     - name: 'telegram'
       webhook_configs:
         - url: 'http://telegram-alertmanager:8080/alerts'
           send_resolved: true
     - name: 'null'

global:
  tolerations:
    - key: infra
      operator: Equal
      value: "true"
      effect: NoSchedule
